import type { VanarAgent } from "@/lib/types/domain";

export const VANAR_AGENTS: VanarAgent[] = [
  {
    id: "rama",
    displayName: "Rama",
    role: "Commander — orchestration & severity",
    model: "mistral-large-latest",
    status: "RUNNING",
    health: "healthy",
    lastAction: "Delegated scan to Angada",
    throughput: 42,
    utilization: 0.62,
    confidence: 0.91,
  },
  {
    id: "hanuman",
    displayName: "Hanuman",
    role: "Watcher — GitHub signals",
    model: "llama-4-scout-17b-16e-instruct",
    status: "RUNNING",
    health: "healthy",
    lastAction: "Webhook triage: push event",
    throughput: 128,
    utilization: 0.44,
    confidence: 0.88,
  },
  {
    id: "angada",
    displayName: "Angada",
    role: "Security — NVD/OSV/npm graph",
    model: "mixtral-8x7b-32768",
    status: "RUNNING",
    health: "healthy",
    lastAction: "CVE correlation complete",
    throughput: 56,
    utilization: 0.71,
    confidence: 0.86,
  },
  {
    id: "jambavan",
    displayName: "Jambavan",
    role: "Analyst — research synthesis",
    model: "mistral-medium-latest",
    status: "IDLE",
    health: "healthy",
    lastAction: "Awaiting delegation",
    throughput: 18,
    utilization: 0.12,
    confidence: 0.84,
  },
  {
    id: "nala",
    displayName: "Nala",
    role: "Patch — codestral remediation",
    model: "codestral-latest",
    status: "RUNNING",
    health: "healthy",
    lastAction: "Generated minimal diff",
    throughput: 24,
    utilization: 0.58,
    confidence: 0.9,
  },
  {
    id: "sugreeva",
    displayName: "Sugreeva",
    role: "QA — CI gatekeeper",
    model: "llama-4-scout-17b-16e-instruct",
    status: "RUNNING",
    health: "healthy",
    lastAction: "Polling GitHub Actions",
    throughput: 33,
    utilization: 0.49,
    confidence: 0.87,
  },
  {
    id: "vibhishana",
    displayName: "Vibhishana",
    role: "Comms — PR/Slack/email",
    model: "llama3-8b-8192",
    status: "IDLE",
    health: "healthy",
    lastAction: "Queued delivery bundle",
    throughput: 12,
    utilization: 0.21,
    confidence: 0.83,
  },
];
